Adding predatorfreak's sha256sum patch with updates for pkgutils version differences

diff --git a/pkgmk.in b/pkgmk.in
--- a/pkgmk.in
+++ b/pkgmk.in
@@ -218,17 +218,63 @@ make_md5sum() {
 	fi
 }
 
+make_sha256sum() {
+	local FILE LOCAL_FILENAMES
+
+	if [ "$source" ]; then
+		for FILE in ${source[@]}; do
+			LOCAL_FILENAMES="$LOCAL_FILENAMES `get_filename $FILE`"
+		done
+
+		sha256sum $LOCAL_FILENAMES | sed -e 's|  .*/|  |' | sort -k 2
+	fi
+}
+
 make_footprint() {
 	pkginfo --footprint $TARGET | \
 		sed "s|\tlib/modules/`uname -r`/|\tlib/modules/<kernel-version>/|g" | \
 		sort -k 3
 }
 
-check_md5sum() {
+check_sum() {
 	local FILE="$PKGMK_WORK_DIR/.tmp"
 
 	cd $PKGMK_ROOT
 	
+	if [ -f $PKGMK_SHA256SUM ]; then
+		make_sha256sum > $FILE.sha256sum
+		sort -k 2 $PKGMK_SHA256SUM > $FILE.sha256sum.orig
+		diff -w -t -U 0 $FILE.sha256sum.orig $FILE.sha256sum | \
+			sed '/^@@/d' | \
+			sed '/^+++/d' | \
+			sed '/^---/d' | \
+			sed 's/^+/NEW       /g' | \
+			sed 's/^-/MISSING   /g' > $FILE.sha256sum.diff
+		if [ -s $FILE.sha256sum.diff ]; then
+			error "Sha256sum mismatch found:"
+			cat $FILE.sha256sum.diff >&2
+
+			if [ "$PKGMK_CHECK_SUM" = "yes" ]; then
+				error "Sha256sum not ok."
+				exit 1
+			fi
+
+			error "Building '$TARGET' failed."
+			exit 1
+		fi
+	else
+		if [ "$PKGMK_CHECK_SUM" = "yes" ]; then
+			if [ "$PKGMK_KEEP_WORK" = "no" ]; then
+				rm -rf $PKGMK_WORK_DIR
+			fi
+			warning "Sha256sum not found."
+			exit 1
+		fi
+
+		warning "Sha256sum not found, creating new."
+		make_sha256sum > $PKGMK_SHA256SUM
+	fi
+			
 	if [ -f $PKGMK_MD5SUM ]; then
 		make_md5sum > $FILE.md5sum
 		sort -k 2 $PKGMK_MD5SUM > $FILE.md5sum.orig
@@ -246,7 +292,7 @@ check_md5sum() {
 				rm -rf $PKGMK_WORK_DIR
 			fi
 
-			if [ "$PKGMK_CHECK_MD5SUM" = "yes" ]; then
+			if [ "$PKGMK_CHECK_SUM" = "yes" ]; then
 				error "Md5sum not ok."
 				exit $E_MD5
 			fi
@@ -255,7 +301,7 @@ check_md5sum() {
 			exit $E_MD5
 		fi
 	else
-		if [ "$PKGMK_CHECK_MD5SUM" = "yes" ]; then
+		if [ "$PKGMK_CHECK_SUM" = "yes" ]; then
 			if [ "$PKGMK_KEEP_WORK" = "no" ]; then
 				rm -rf $PKGMK_WORK_DIR
 			fi
@@ -267,11 +313,11 @@ check_md5sum() {
 		make_md5sum > $PKGMK_MD5SUM
 	fi
 
-	if [ "$PKGMK_CHECK_MD5SUM" = "yes" ]; then
+	if [ "$PKGMK_CHECK_SUM" = "yes" ]; then
 		if [ "$PKGMK_KEEP_WORK" = "no" ]; then
 			rm -rf $PKGMK_WORK_DIR
 		fi
-		info "Md5sum ok."
+		info "Checksums ok."
 		exit 0
 	fi
 }
@@ -370,8 +416,8 @@ make_work_dir() {
 	remove_work_dir
 	mkdir -p $SRC $PKG
 
-	if [ "$PKGMK_IGNORE_MD5SUM" = "no" ]; then
-		check_md5sum
+	if [ "$PKGMK_IGNORE_SUM" = "no" ]; then
+		check_sum
 	fi
 }
 
@@ -551,9 +597,9 @@ print_help() {
 	echo "  -uf,  --update-footprint    update footprint using result from last build"
 	echo "  -if,  --ignore-footprint    build package without checking footprint"
 	echo "  -in,  --ignore-new          build package, ignore new files in a footprint missmatch"
-	echo "  -um,  --update-md5sum       update md5sum"
-	echo "  -im,  --ignore-md5sum       build package without checking md5sum"
-	echo "  -cm,  --check-md5sum        do not build, only check md5sum"
+	echo "  -um,  --update-sums         update checksums"
+	echo "  -im,  --ignore-sums         build package without checking checksums"
+	echo "  -cm,  --check-sums          do not build, only check checksums"
 	echo "  -ns,  --no-strip            do not strip executable binaries or libraries"
 	echo "  -f,   --force               build package even if it appears to be up to date"
 	echo "  -c,   --clean               remove package and downloaded files"
@@ -587,12 +633,12 @@ parse_options() {
 				PKGMK_IGNORE_FOOTPRINT="yes" ;;
 			-in|--ignore-new)
 				PKGMK_IGNORE_NEW="yes" ;;
-			-um|--update-md5sum)
-				PKGMK_UPDATE_MD5SUM="yes" ;;
-			-im|--ignore-md5sum)
-				PKGMK_IGNORE_MD5SUM="yes" ;;
-			-cm|--check-md5sum)
-				PKGMK_CHECK_MD5SUM="yes" ;;
+			-um|--update-sums|--update-md5sum)
+				PKGMK_UPDATE_SUM="yes" ;;
+			-im|--ignore-sums|--ignore-md5sum)
+				PKGMK_IGNORE_SUM="yes" ;;
+			-cm|--check-sums|--check-md5sum)
+				PKGMK_CHECK_SUM="yes" ;;
 			-ns|--no-strip)
 				PKGMK_NO_STRIP="yes" ;;
 			-f|--force)
@@ -672,11 +718,13 @@ main() {
 		exit 0
 	fi
 	
-	if [ "$PKGMK_UPDATE_MD5SUM" = "yes" ]; then
+	if [ "$PKGMK_UPDATE_SUM" = "yes" ]; then
 		download_source
 		check_file "$PKGMK_MD5SUM"
 		make_md5sum > $PKGMK_MD5SUM
 		info "Md5sum updated."
+		make_sha256sum > $PKGMK_SHA256SUM
+		info "Sha256sum updated."
 		exit 0
 	fi
 	
@@ -702,7 +750,7 @@ main() {
 		exit 0
 	fi
 	
-	if [ "`build_needed`" = "no" ] && [ "$PKGMK_FORCE" = "no" ] && [ "$PKGMK_CHECK_MD5SUM" = "no" ]; then
+	if [ "`build_needed`" = "no" ] && [ "$PKGMK_FORCE" = "no" ] && [ "$PKGMK_CHECK_SUM" = "no" ]; then
 		info "Package '$TARGET' is up to date."
 	else
 		download_source
@@ -728,6 +776,7 @@ PKGMK_CONFFILE="/etc/pkgmk.conf"
 PKGMK_PKGFILE="Pkgfile"
 PKGMK_FOOTPRINT=".footprint"
 PKGMK_MD5SUM=".md5sum"
+PKGMK_SHA256SUM=".sha256sum"
 PKGMK_NOSTRIP=".nostrip"
 
 PKGMK_SOURCE_MIRRORS=()
@@ -748,9 +797,9 @@ PKGMK_IGNORE_FOOTPRINT="no"
 PKGMK_IGNORE_NEW="no"
 PKGMK_FORCE="no"
 PKGMK_KEEP_WORK="no"
-PKGMK_UPDATE_MD5SUM="no"
-PKGMK_IGNORE_MD5SUM="no"
-PKGMK_CHECK_MD5SUM="no"
+PKGMK_UPDATE_SUM="no"
+PKGMK_IGNORE_SUM="no"
+PKGMK_CHECK_SUM="no"
 PKGMK_NO_STRIP="no"
 PKGMK_CLEAN="no"
 
